import Head from "next/head";
import Link from "next/link.js";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { motion } from "framer-motion";
import { container, item } from "../animation";

export default function Home() {
  return (
    <>
      <Head>
        <title>LN DEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <div className="home__lines"></div>
        <div className="home__container">
          <h1>
            HEY, I’M <span> LEONEL NGOYA </span>
            BUT YOU CAN CALL ME <span> LN </span>
          </h1>
          <p>
            I’m a Front-end Developer & Web Integrator, <br /> I’m passionate
            about creating beautiful, intuitive and responsive websites.
          </p>
          <Link href="/contact">
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M19.7501 11.7258L4.75012 11.7258"
                stroke="#130F26"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <path
                d="M13.6998 5.70124C13.6998 5.70124 19.7498 8.96224 19.7498 11.7242C19.7498 14.4882 13.6998 17.7502 13.6998 17.7502"
                stroke="#130F26"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
            <span>About me</span>
          </Link>
        </div>
      </main>
    </>
  );
}
